apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
  namespace: demo
  labels:
    app: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: demoapp
        app.kubernetes.io/name: featuredemo
        app.kubernetes.io/version: V1
        app: demoapp
      # This is the annotation for OpenFeature Operator
      annotations:     
        core.openfeature.dev/enabled: "true"
        core.openfeature.dev/flagsourceconfiguration: "flags/flagsourceconfiguration-sample"     
    spec:
      containers:
      - name: demoapp
        image: aloisreitbauer/featuredemo:V1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: FLAGD_PORT
          value: "8030"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
