apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: demo
spec:
  replicas: 5
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
      - setWeight: 50
      - pause: { duration: 2m }
      - analysis:
          templates:
          - templateName: health-analysis
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: demoapp
        app.kubernetes.io/name: featuredemo
        app.kubernetes.io/version: pre
        app: demoapp
        keptn.sh/pre-deployment-tasks: load-test
        keptn.sh/post-deployment-evaluations: demoapp-healty-check
      # This is the annotation for OpenFeature Operator
      annotations:     
        openfeature.dev/enabled: "true"
        openfeature.dev/flagsourceconfiguration: "demo/flagsourceconfiguration-sample"     
    spec:
      containers:
      - name: demoapp
        image: aloisreitbauer/featuredemo:V2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: FLAGD_PORT
          value: "8030"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.keptn-lifecycle-toolkit-system:4317"     
        - name: OTEL_SERVICE_NAME
          value: "demoapp"     
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: health-analysis
  namespace: demo
spec:
  metrics:
  - name: success-rate
    interval: 10s
    count: 1
    successCondition: asFloat(result) < 0.3
    provider:
      web:
        url: "http://keptn-klt-metrics-operator-service.keptn-lifecycle-toolkit-system:9999/api/v1/metrics/demo/demoapp-latency"
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.value}"