apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
  namespace: demo
  labels:
    app: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: demoapp
        app.kubernetes.io/name: featuredemo
        app.kubernetes.io/version: 1.1.0
        app: demoapp
        keptn.sh/post-deployment-tasks: load-test
        keptn.sh/post-deployment-evaluations: demoapp-healty-check
      # This is the annotation for OpenFeature Operator
      annotations:     
        openfeature.dev/enabled: "true"
        openfeature.dev/flagsourceconfiguration: "demo/flagsourceconfiguration-sample"     
    spec:
      containers:
      - name: demoapp
        image: aloisreitbauer/featuredemo:V1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: FLAGD_PORT
          value: "8030"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.keptn-lifecycle-toolkit-system:4317"     
        - name: OTEL_SERVICE_NAME
          value: "demoapp"     
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3