apiVersion: core.openfeature.dev/v1alpha2
kind: FeatureFlagConfiguration
metadata:
  name: featureflagconfiguration-sample
  namespace: demo
spec:
  featureFlagSpec:
    flags:
      my-flag:
        state: "ENABLED"
        variants:
          "true": true
          "false": false
        defaultVariant: "false"
        targeting: {}
      slowFlag:
        state: "ENABLED"
        variants:
          "true": true
          "false": false
        defaultVariant: "false"
        targeting: {}
